name: CI

on:
  push:
    branches: [main]

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: dnf install -y git
      - run: dnf install -y --exclude root-fonts --skip-broken \*-opentype-fonts
      - run: dnf install -y --exclude root-fonts --skip-broken \*-fonts \*-fonts-common \*-fonts-all
      - run: dnf install -y mono-complete
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: dnf install -y make
      - run: make -C FV USE_MONO_SECURITY=true
      - run: ln -s $GITHUB_WORKSPACE/FV/bin/fedora-fc35-x64/libfreetype.so.6.18.0 libfreetype.so.6
      - env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE
        run: find /usr/share/wine/fonts/times.ttf -exec mono FV/bin/FontValidator.exe -file {} -stdout \;


  ubuntu-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cat /etc/os-release
      - run: sudo apt-get -y install fonts-\*
      - run: sudo apt-get -y install mono-complete
      - run: sudo apt-get -y install make
      - run: make -C FV USE_MONO_SECURITY=true
      - run: ln -s ${{ github.workspace }}/FV/bin/ubuntu-18.04-x64/libfreetype.so.6.17.1 libfreetype.so.6
      - env:
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: find /usr/share/wine/fonts/wingding.ttf -exec mono FV/bin/FontValidator.exe -file /usr/share/wine/fonts/wingding.ttf -stdout \;
