name: CI

on:
  push:
    paths:
      - '.github/**'
    label:
      types: [created]
    tags:
      - RUN*


jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: dnf install -y git
      - run: dnf install -y --exclude root-fonts --skip-broken \*-opentype-fonts
      - run: dnf install -y --exclude root-fonts --skip-broken \*-fonts \*-fonts-common \*-fonts-all
      - run: dnf install -y mono-complete
      - run: dnf install -y texlive-collection-\*
      - run: dnf install --exclude texlive\*-doc -y texlive\*
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: dnf install -y make
      - run: make -C FV USE_MONO_SECURITY=true
      - run: dnf upgrade -y AR/RPMS/x86_64/freetype-2.13.2-2p.fc38.x86_64.rpm
      - run: find /usr/share/wine/fonts/times.ttf -exec mono FV/bin/FontValidator.exe -file {} -stdout \;
      - run: mkdir temp-f1 temp-f2
      - run: env TEMP=${GITHUB_WORKSPACE}/temp-f1 find /usr/share/wine/fonts/times.ttf -exec mono FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \;
      - run: env TEMP=${GITHUB_WORKSPACE}/temp-f2 find /usr/share/ -type f -iname '*.[to]t[fc]' -exec mono FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \; > /dev/null
      - run: find /usr/share/ -type f -iname '*.[to]t[fc]' -exec rpm -qf "{}" \; | sort | uniq > temp-f2/package-list
      - run: dnf install -y dos2unix
      - run: rm temp-*/*.report.html temp-*/*.report.txt
      - run: dos2unix temp-*/*.report.xml
      - uses: actions/upload-artifact@v3
        with:
          name: fedora-1
          path: temp-f1
      - uses: actions/upload-artifact@v3
        with:
          name: fedora-2
          path: temp-f2


  ubuntu-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cat /etc/os-release
      - run: sudo apt-get update
      - run: sudo apt-get -y install fonts-\*
      - run: sudo apt-get -y install ttf-\*
      - run: sudo apt-get -y install texlive-full
      - run: sudo apt-get -y install mono-complete
      - run: sudo apt-get -y install make
      - run: make -C FV USE_MONO_SECURITY=true
      - run: ln -s ${{ github.workspace }}/FV/bin/ubuntu-18.04-x64/libfreetype.so.6.17.1 libfreetype.so.6
      - run: mkdir temp-t1 temp-t2
      - env:
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: find /usr/share/wine/fonts/wingding.ttf -exec mono FV/bin/FontValidator.exe -file {} -stdout \;
      - env:
          TEMP: ${{ github.workspace }}/temp-t1
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: find /usr/share/wine/fonts/wingding.ttf -exec mono FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \;
      - env:
          TEMP: ${{ github.workspace }}/temp-t2
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: find /usr/share/ -type f -iname '*.[to]t[fc]' -exec mono FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \; > /dev/null
      - run: sudo apt-get -y install dos2unix
      - run: rm temp-*/*.report.html temp-*/*.report.txt
      - run: dos2unix temp-*/*.report.xml
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-1
          path: temp-t1
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-2
          path: temp-t2


  windows-job:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: bash -c 'find C:/windows/fonts'
      - run: bash -c 'tar -czpvf windows-fonts.tgz C:/windows/fonts'
#      - run: bash -c "find /usr/share/ -type f -iname '*.[to]t[fc]' -exec FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \; > /dev/null"
      - uses: actions/upload-artifact@v3
        with:
          name: windows-fonts
          path: windows-fonts.tgz

  mac-job:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo find /Library /System/Library/ /Applications/ -type f -iname '*.[to]t[fc]' | tee mac-fonts
      - run: cat mac-fonts | zip -@ mac-fonts.zip
      - uses: actions/upload-artifact@v3
        with:
          name: mac-fonts-11
          path: mac-fonts.zip

  mac-job:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo find /Library /System/Library/ /Applications/ -type f -iname '*.[to]t[fc]' | tee mac-fonts
      - run: cat mac-fonts | zip -@ mac-fonts.zip
      - uses: actions/upload-artifact@v3
        with:
          name: mac-fonts-12
          path: mac-fonts.zip

  mac-job:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo find /Library /System/Library/ /Applications/ -type f -iname '*.[to]t[fc]' | tee mac-fonts
      - run: cat mac-fonts | zip -@ mac-fonts.zip
      - uses: actions/upload-artifact@v3
        with:
          name: mac-fonts-13
          path: mac-fonts.zip

  mac-job:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo find /Library /System/Library/ /Applications/ -type f -iname '*.[to]t[fc]' | tee mac-fonts
      - run: cat mac-fonts | zip -@ mac-fonts.zip
      - uses: actions/upload-artifact@v3
        with:
          name: mac-fonts-14
          path: mac-fonts.zip
