name: CI

on:
  push:
    branches: [main]

jobs:
  fedora-job:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: cat /etc/os-release
      - run: dnf install -y git
      - run: dnf install -y --exclude root-fonts --skip-broken \*-opentype-fonts
      - run: dnf install -y --exclude root-fonts --skip-broken \*-fonts \*-fonts-common \*-fonts-all
      - run: dnf install -y mono-complete
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: dnf install -y make
      - run: make -C FV USE_MONO_SECURITY=true
      - run: ln -s ${{ github.workspace }}/fedora-fc35-x64/* libfreetype.so
      - env:
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: mono FV/bin/FontValidator.exe -file /usr/share/wine/fonts/times.ttf -stdout


  ubuntu-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cat /etc/os-release
      - run: sudo apt-get -y install fonts-\*
      - run: sudo apt-get -y install mono-complete
      - run: sudo apt-get -y install gmake
      - run: make -C FV USE_MONO_SECURITY=true
      - run: ln -s ${{ github.workspace }}/ubuntu-18.04-x64/* libfreetype.so
      - env:
          LD_LIBRARY_PATH: ${{ github.workspace }}
        run: mono FV/bin/FontValidator.exe -file /usr/share/wine/fonts/times.ttf -stdout
