name: FONTS

on:
  push:
    paths:
      - '.github/**'
    label:
      types: [created]

jobs:
  windows-job:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: bash -c 'find C:/windows/fonts'
      - run: bash -c 'tar -czpvf windows-fonts.tgz C:/windows/fonts'
#      - run: bash -c "find /usr/share/ -type f -iname '*.[to]t[fc]' -exec FV/bin/FontValidator.exe -test-parms 1.py -file {} -stdout \; > /dev/null"
      - uses: actions/upload-artifact@v3
        with:
          name: windows-fonts
          path: windows-fonts.tgz

  mac-job:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo find /Library /System/Library/ /Applications/ -type f -iname '*.[to]t[fc]' | tee mac-fonts
      - run: tar -cJpf mac-fonts.txz -T mac-fonts
      - uses: actions/upload-artifact@v3
        with:
          name: mac-fonts-14
          path: |
            mac-fonts
            mac-fonts.txz
